"""crate user table

Revision ID: 1537191f1d98
Revises: 
Create Date: 2025-01-24 16:42:04.758646

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1537191f1d98"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    stmt = (
        "INSERT INTO users (id, role, username, password) VALUES "
        + "(1, 'user', 'user', '$2b$12$6Bc6RoBww9be3bnCOd4gjeBr6eQJKqDJGPhb8pcgkF3oIaQXWTWpC'), "
        + "(2, 'admin', 'admin', '$2b$12$xhKvC54J1FA48MwbzTW4Fupnm309n6yaWPGcCuiTnzS2qH1YNtV/a');"
    )

    op.execute(stmt)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
