FROM python:3.12-slim
COPY requirements.txt /tmp

WORKDIR /app
RUN set -x && \
    apt-get update && \
    pip install --upgrade pip && \
    pip install -r /tmp/requirements.txt

COPY ./alembic /app/alembic
COPY ./src/models /app/src/models
COPY ./src/shared/base_config.py /app/src/shared/base_config.py
COPY alembic.ini /app/alembic.ini
